### PR TITLE
Major Refactor

### PR DESCRIPTION
**Pull request by mgarciadelojo**
Mainly, the things I tried to do are:
- Use of PSR-4 Autoloader.
- Get more than 420 activities at a time. In this version, no matter how many activities the user has, the library returns all of them.
- I tried to follow PSR conventions and documentations properly. The class interface haven't changed to maintain backwards compatibility.
- Added countable behavior to RuntasticActivityList to allow devs to use `count`.
- Changed README to be more concise and simple. Basic examples added with PSR-4 autoloading.

Of couse, comments are allowed :)

### CODE REVIEW

**Comment by mgarciadelojo** [comment]
Hi @timoschlueter,

Could you take a look on it? What do you think?
Ideas and comments are welcome :)

Cheers,

**Comment by timoschlueter** [comment]
Hi Manuel,

i finally got to look at your code. Great job! A lot more structured than my original class.
It worked without any problems. I will merge the pull request immediately :)

Regards,
Timo

**Comment by mgarciadelojo** [comment]
Hi @timoschlueter,

Great!! I'm glad you liked my work. There is still some changes I wanted to do in the class by the way, but I'll create another pull request in a few weeks. Did you notice that now the code can fetch more than 420 activities?

Regards,

**Comment by timoschlueter** [comment]
Hi @mgarciadelojo,

i did notice it. In fact, thats the first thing i tried. I logged in with my credentials and fetched all my activities. Worked like a charm :)

**Pull request merged**
